baseURL = "http://example.org/"
languageCode = "en-us"
title = "bwynn.io"
theme = "hugo-coder"

[params]
    author="Brian Wynn"
    info="UI Engineer"
    description="The personal website for Brian Wynn, javascript and golang software engineer."

    footercontent="©2020 Brian Wynn"

# social
[[params.social]]
    name="Github"
    icon="fab fa-github fa-2x"
    weight=2
    url="https://github.com/bwynn/"
[[params.social]]
    name="Twitter"
    icon="fab fa-twitter fa-2x"
    weight=2
    url="https://twitter.com/users/bwynn_dev"

[[menu.main]]
    name="Blog"
    weight=1
    url="/posts/"
[[menu.main]]
    name="About"
    weight=1
    url="/about"
[[menu.main]]
    name="Tutorials"
    weight=1
    url="/tutorials/"

