baseURL = "https://bwynn.io/"
languageCode = "en-us"
title = "bwynn.io"
theme = "hugo-coder"

paginate = 10

[params]
    author="Brian Wynn"
    info="UI Engineer"
    description="The personal website for Brian Wynn, javascript and golang software engineer."

    footercontent="Be Excellent To Each Other"

    hideCredits = true
    hideCopyright = true

    custom_css = ["main.css"]

[params.csp]
    scriptsrc = [
        "'self'",
        "https://bwynn.io",
        "https://www.bwynn.io"
    ]

# social
[[params.social]]
    name="Github"
    icon="fab fa-github fa-2x"
    weight=2
    url="https://github.com/bwynn/"
[[params.social]]
    name="Twitter"
    icon="fab fa-twitter fa-2x"
    weight=2
    url="https://twitter.com/bwynn_dev"
[[params.social]]
    name="Codepen"
    icon="fab fa-codepen fa-2x"
    weight=2
    url="https://codepen.io/b_wynn"
[[params.social]]
    name="Repl.it"
    icon="fas fa-robot fa-2x"
    weight=2
    url="https://repl.it/@bwynn"

[[menu.main]]
    name="Blog"
    weight=1
    url="/posts/"
[[menu.main]]
    name="About"
    weight=1
    url="/about"
[[menu.main]]
    name="Tutorials"
    weight=1
    url="/tutorials/"

